create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null,
  role text not null default 'admin' check (role in ('admin', 'manager')),
  auth_provider text not null default 'password',
  google_id text unique,
  is_active integer not null default 1 check (is_active in (0, 1)),
  created_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('rental', 'airbnb', 'apartment')),
  location text,
  address text,
  description text,
  status text not null default 'active',
  monthly_rent numeric(14, 2) not null default 0 check (monthly_rent >= 0),
  rules text,
  manager_name text,
  manager_phone text,
  manager_email text,
  caretaker_name text,
  caretaker_phone text,
  caretaker_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete restrict,
  house_id text not null,
  rent_amount numeric(14, 2) not null default 0 check (rent_amount >= 0),
  water_billing_type text not null default 'included' check (water_billing_type in ('included', 'fixed', 'metered')),
  water_rate numeric(14, 2) not null default 0 check (water_rate >= 0),
  water_notes text,
  status text not null default 'ready' check (status in ('ready', 'maintenance')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, house_id)
);

create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete restrict,
  unit_id bigint references public.units(id) on delete restrict,
  name text not null,
  email text,
  phone text,
  type text not null default 'long-term' check (type in ('long-term', 'short-term')),
  lease_start date,
  lease_end date,
  rent_amount numeric(14, 2) not null default 0,
  deposit_amount numeric(14, 2) not null default 0,
  physical_contract_received integer not null default 0 check (physical_contract_received in (0, 1)),
  contract_reference text,
  onboarding_sent_at timestamptz,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete restrict,
  tenant_id bigint references public.tenants(id) on delete restrict,
  amount numeric(14, 2) not null check (amount > 0),
  payment_type text not null default 'rent' check (payment_type in ('deposit', 'rent', 'water', 'other')),
  status text not null default 'pending' check (status in ('paid', 'pending', 'overdue', 'partial')),
  method text check (method in ('mpesa', 'bank', 'cash', 'other')),
  payment_date date,
  due_date date,
  notes text,
  receipt_notifications_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete restrict,
  unit_id bigint references public.units(id) on delete restrict,
  title text not null,
  description text,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  category text check (category in ('plumbing', 'electrical', 'structural', 'appliance', 'pest', 'other')),
  reported_date date not null default current_date,
  resolved_date date,
  notes text,
  repair_cost numeric(14, 2) not null default 0 check (repair_cost >= 0),
  expense_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete restrict,
  unit_id bigint references public.units(id) on delete restrict,
  issue_id bigint references public.issues(id) on delete set null,
  category text not null check (category in ('repair', 'septic', 'manager_salary', 'caretaker', 'cleaner', 'custom')),
  description text not null,
  amount numeric(14, 2) not null check (amount > 0),
  expense_date date not null,
  notes text,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.approval_requests (
  id bigint generated by default as identity primary key,
  requested_by bigint not null references public.users(id) on delete restrict,
  entity_type text not null check (entity_type in ('property', 'tenant', 'unit', 'expense', 'issue', 'payment')),
  entity_id text,
  action text not null check (action in ('create', 'update', 'delete')),
  payload_json text not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  reviewed_by bigint references public.users(id) on delete restrict,
  review_note text,
  reviewed_at timestamptz,
  executed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.approval_comments (
  id bigint generated by default as identity primary key,
  approval_id bigint not null references public.approval_requests(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete restrict,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_jobs (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete set null,
  channel text not null check (channel in ('email', 'sms')),
  notification_type text not null,
  recipient text not null,
  subject text,
  body text not null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  scheduled_for timestamptz,
  sent_at timestamptz,
  error text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.issues
  drop constraint if exists issues_expense_id_fkey;
alter table public.issues
  add constraint issues_expense_id_fkey foreign key (expense_id) references public.expenses(id) on delete set null;

create unique index if not exists idx_users_google_id on public.users(google_id) where google_id is not null;
create unique index if not exists idx_one_active_tenant_per_unit on public.tenants(unit_id) where unit_id is not null and status = 'active';
create index if not exists idx_units_property_id on public.units(property_id);
create index if not exists idx_units_status on public.units(status);
create index if not exists idx_tenants_unit_id on public.tenants(unit_id);
create index if not exists idx_tenants_property_id on public.tenants(property_id);
create index if not exists idx_payments_property_id on public.payments(property_id);
create index if not exists idx_payments_tenant_id on public.payments(tenant_id);
create index if not exists idx_payments_status on public.payments(status);
create index if not exists idx_issues_property_id on public.issues(property_id);
create index if not exists idx_issues_status on public.issues(status);
create index if not exists idx_issues_unit_id on public.issues(unit_id);
create index if not exists idx_expenses_property_id on public.expenses(property_id);
create index if not exists idx_expenses_issue_id on public.expenses(issue_id);
create index if not exists idx_approvals_status on public.approval_requests(status);
create index if not exists idx_approvals_requested_by on public.approval_requests(requested_by);
create index if not exists idx_approval_comments_approval_id on public.approval_comments(approval_id);
create index if not exists idx_notification_jobs_status on public.notification_jobs(status);
create index if not exists idx_notification_jobs_tenant_id on public.notification_jobs(tenant_id);

-- The API uses a server-only Postgres connection. Block direct Data API access
-- until explicit, user-scoped Supabase Auth policies are added for any client.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'properties', 'units', 'tenants', 'payments', 'issues',
    'expenses', 'approval_requests', 'approval_comments', 'notification_jobs'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end;
$$;

-- Keep future public tables and identity sequences closed to browser roles too.
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

