-- Link the application's server-side account to the Supabase Auth identity
-- supplied during the owner-account setup. The API still owns the session
-- and password flow, so the Auth UUID is only an identity binding.
alter table public.users
  add column if not exists auth_user_id uuid unique;

create unique index if not exists idx_users_auth_user_id
  on public.users(auth_user_id)
  where auth_user_id is not null;

create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  requested_by bigint references public.users(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'completed', 'expired', 'cancelled')),
  token_hash text unique,
  token_expires_at timestamptz,
  reviewed_by bigint references public.users(id) on delete set null,
  review_note text,
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_one_open_password_reset_per_user
  on public.password_reset_requests(user_id)
  where status in ('pending', 'approved');

create index if not exists idx_password_reset_requests_status
  on public.password_reset_requests(status, requested_at desc);

create index if not exists idx_password_reset_requests_user_id
  on public.password_reset_requests(user_id);

alter table public.password_reset_requests enable row level security;
revoke all on table public.password_reset_requests from anon, authenticated;

